ubergrape/grape-web-client

src/components/message-parts/link-attachments/parts/Embed.js

ubergrape/grape-web-client/issues/361

Prevent scrolling in Link Attachments Embeds

---

src/actions/login.js
src/utils/backend/api/xhr.js

https://jira.ubergrape.com/browse/GRAPE-14838

If SSO enabled open link to login page with path /sso/sso

---

src/components/login/Login.js

https://jira.ubergrape.com/browse/GRAPE-14745

update style to make sure the text doesn't get cut off

---

src/components/history/ReadRow.js

https://jira.ubergrape.com/browse/GRAPE-7141

fixed bug where message was marked as read while focus was on another window

---

package-lock.json
package.json
styleguide.config.js

@AleshaOleg I was exploring Styleguide options with Carina today and in the process we updated this dependency

upgrade styleguidist

---

src/components/sidebar/TabbedContent.js

Just a temporary PR, to investigate how it can be done more accurately

Fix minWidth for tab in sidebar

---

src/components/browser-notification/BrowserNotification.js

https://github.com/markdown-it/markdown-it#init-with-presets-and-options

Enabled typography transformations frp markdown-it

---

i18n/translations/de.json
i18n/translations/en.json
src/components/footer/grape-input/utils.js
src/components/grapedown/renderers.js
src/i18n/de.js
src/i18n/en.js

https://jira.ubergrape.com/browse/GRAPE-15101

Link username in quote to private message convo

---

i18n/translations/de.json
i18n/translations/en.json

Pull request created by LingoHub based on branch master

LingoHub based on master

---

package.json
yarn.lock

See https://nodejs.org/en/blog/vulnerability/june-2018-security-releases/

Node version security upgrade

---

src/actions/mentions.js

Sorry, understood an issue in a wrong way. Return back previous logic, how it was.
https://jira.ubergrape.com/browse/GRAPE-15519

Swap back params for mentionTypes field

---

src/components/tooltip/Tooltip.js

@AleshaOleg please double-check that there is no Tooltip using onClick

change tooltip to be a div and not accept an onclick handler

---

src/components/history/messages/activity/ActivityMessage.js
src/components/history/messages/regular/Menu.js
src/components/history/messages/regular/RegularMessage.js

hide quote and pin in case the message only contains link attachments e.g. an uploaded image

---

i18n/translations/de.json
i18n/translations/en.json

Pull request created by LingoHub based on branch production

LingoHub based on production

---

package.json
yarn.lock

@AleshaOleg with this PR you can use Node 10 again for the proxy

upgrade proxy

---

i18n/translations/de.json
i18n/translations/en.json
src/components/browser-notification/BrowserNotification.js
src/constants/notification.js
src/i18n/de.js
src/i18n/en.js

This makes sure unknown notification events do not crash the app and already implements the incoming call event.

Fix crashing on unexpected notification

---

src/reducers/history.js

Reverts ubergrape/grape-web-client#932

Revert "Prevent race condition when server trying to mark channel as read, bu…"

---

src/actions/common.js

This isn't tested yet. Victor first needs to deploy it to staging, then we can test it there and merge it.

use the new grapecallUrl

---

src/actions/utils.js
src/components/history/History.js
src/components/history/NoContent.js
src/components/history/Row.js
src/components/history/messages/activity/ActivityMessage.js
src/components/history/messages/activity/Menu.js
src/components/history/messages/regular/Menu.js
src/components/history/messages/regular/RegularMessage.js
src/components/sidebar/Sidebar.js
src/components/sidebar/channel-members/ChannelMembers.js
src/components/sidebar/channel-members/User.js
src/components/sidebar/room-info/RoomActions.js
src/components/sidebar/room-info/RoomInfo.js
src/selectors/index.js

Reverts ubergrape/grape-web-client#1021

Revert "Setup message permissions"

---

package.json
yarn.lock

Reverts ubergrape/grape-web-client#974

Revert "Bump webpack-dev-server from 2.11.2 to 3.1.11"

---

package.json
src/components/new-conversation-dialog/NewConversationDialog.js
src/components/new-conversation-dialog/create-room/index.js
src/components/new-conversation-dialog/create-room/theme.js
src/components/new-conversation-dialog/groups/index.js

a couple of small fixes. one commit per fix.

NCD improvements 1

---

src/components/new-conversation-dialog/NewConversationDialog.js
src/components/new-conversation-dialog/create-room/index.js

I gave the new conversation dialog an id to fix this. that looked like the most straightforward way to solve this

Fix group creation for non-English languages GRAPE-19563

---

src/components/new-conversation-dialog/people/index.js

Fix opening channel when clicking on user

---

src/actions/navigation.js
src/utils/backend/api/search.js

Use new search_overview API for the sidebar

---

src/actions/newConversation.js

Prevent outdated API responses from updating the search results

---

src/components/new-conversation-dialog/create-group/NoRowsRenderer.js
src/components/new-conversation-dialog/people/index.js

fixes two bugs reported in one issue
* Show organization name in string properly
* Show a different error message if there are no members yet in this organization

Bug/empty org/grape 19609

---

src/components/new-conversation-dialog/create-group/RowRenderer.js
src/components/new-conversation-dialog/people/RowRenderer.js

Use display_name from server

---

bin/release.sh
docs/release.md

Automates most steps in the release process. unicorn strings are hardcoded but I don't mind

Add release script

---

docs/debugging.md
src/utils/backend/WampClient.js

https://jira.ubergrape.com/browse/GRAPE-19537

Task/reconnect logs/grape 19537
